language: go
go_import_path: github.com/omio-labs/myke
go:
  - 1.13
env:
  - GO111MODULE=on
script:
  - gofmt -d -s -e . 2>&1 | tee -a fmt.out
  - test ! -s fmt.out
  - go run golang.org/x/lint/golint -set_exit_status .
  - go test -coverprofile=coverage.txt -coverpkg=github.com/omio-labs/myke/core,github.com/omio-labs/myke/cmd -covermode=atomic -timeout 10s -v ./...
  - bin/cross-compile.sh "$TRAVIS_TAG-$TRAVIS_COMMIT"
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: k1rJLldr7WPfPHpURdb6XWUsJ3X+dpJ/UTfsurQ6T/NLqX+PAstiJGK4MZCO1K2YetZvH0A/wzzR6kM5VVDeVXthWB1m3OKQ0qH+/23EjSj7H72EpHWKLYhBlVlqrhwP2McYBd8V6xSalcQzTwS73IgCK0i7xMaVGd8cydmhEHI3cZpQANLvLYWeId1AcTOejkFHZEnZususJi6Vis/HkwEU3Pk7vAO6u8eYqq4ZX2Bk/4ThSVjF+bHvMK7auv6Pn84XuTH8tVqpmVqHqHbMegP6lBrVnjSeSXfc/Rs7hTACXZymNyKtzIfeSsTzY25bRneYmHQFGxmOfSs9X+F6Ky5YswyhR/p/z9gytvzOyWQIS42PeOrQC6aHQwt5/zLazIyqFjTm1p6mbN6Hob6WYhjcv5/nRpyyDCa8/svqrm+mIAtI3Dno1TWmTFP9EK/a64cpWf4UgHtpVS5abBWavelLmY468H0bEtdOSo1uhQbDXlIz/pZXfDBLRtEqU0pWRqIZJvtDhb8SQeuVbI+eARrKjM/T2RYgMm3i6kzZuiKrNw0bLxJJKFY27g25ew7kpeIwwAn1eVHwMDin6c4owsYzxh7u63EvPXM3Cr4MxuBvOo5Q1DpdbTtRQLTkNT8yIUkgPJcfNg1M6mgCcdG5B7u+CMQLKXtMtu7TVykbt3s=
  file:
    - bin/myke_darwin_amd64
    - bin/myke_linux_amd64
    - bin/myke_windows_amd64.exe
  on:
    repo: omio-labs/myke
    branch: none
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].+$"
notifications:
  email: false
