version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\goeuro\myke

environment:
  GOPATH: C:\gopath

# Uncomment following line if you are willing to debug on the build machine.
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- set PATH=%GOPATH%\bin;C:\go\bin;%WINDIR%;%WINDIR%\System32;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin
- go version
- go env
- sh c:\gopath\src\github.com\goeuro\myke\bin\init.sh

build_script:
- gofmt -d -s -e . 2>&1 | tee -a fmt.out
- test ! -s fmt.out
- golint -set_exit_status .
- go test -timeout 10s -v ./...

